name: Docker Build and Push

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Build, tag, and push Docker image to Amazon ECR
      env:
        # ECR_REGISTRY: ${{ steps.get-ecr-registry.outputs.registry }}
        ECR_REGISTRY: 147017997364.dkr.ecr.eu-north-1.amazonaws.com
        # ECR_REGISTRY: ${{ env.ECR_REGISTRY }}
        ECR_REPOSITORY: booking-api-ecr
        IMAGE_TAG: ${{ github.ref_name }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:0.0.1 .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:0.0.1
